apiVersion: apps/v1
kind: Deployment
metadata:
  name: oddschecker-deployment
spec:
  selector:
    matchLabels:
      app: oddschecker-api
  replicas: {{ .Values.autoscaling.minReplicas }}
  template:
    metadata:
      labels:
        app: oddschecker-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8090"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            timeoutSeconds: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            timeoutSeconds: 3
            periodSeconds: 15
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c",  "sleep 30"]
