apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grafana
  ports:
    - name: promui
      protocol: TCP
      port: 3000
      targetPort: 3000
