kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: prometheus
  ports:
    - name: promui
      protocol: TCP
      port: 9090
      targetPort: 9090