image:
  repository: "koudocker/oddschecker"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8090

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  #targetCPUUtilizationPercentage: 1
  targetMemoryUtilizationPercentage: 10